Repository ChildMindInstitute/mindlogger-backend, pull requests merged in 2021-02, with the labels that each got.

#982 Remove default folders for account creation
  girderformindlogger/models/user.py
Labels: CMI Milestone 3, Python, backend, bug

#983 Replace the 'MRN' with the 'Secret User ID' on the 'Try again' popup
  girderformindlogger/i18n/locales/en.py
Labels: CMI Milestone 3, bug

#975 Bugfix/1340
  girderformindlogger/api/v1/applet.py
  girderformindlogger/api/v1/response.py
  girderformindlogger/api/v1/user.py
  girderformindlogger/external/notification.py
  girderformindlogger/models/applet.py
  girderformindlogger/models/events.py
  girderformindlogger/models/item.py
  girderformindlogger/models/protocol.py
  girderformindlogger/utility/jsonld_expander.py
  girderformindlogger/utility/response.py
Labels: CMI Milestone 3

#970 Fix apns expiration
  girderformindlogger/api/v1/notification.py
  girderformindlogger/external/notification.py
Labels: CMI Milestone 3

#988 Fix applet user invitation
  girderformindlogger/api/v1/applet.py
Labels: CMI Milestone 3, Python, backend, bug
